### ISSUE TITLE
Issue after yarn start

### ISSUE THREAD

**Issue by z3rotto** [onepointAI/onepoint#22]
I can't proceed and showed this issue up.

An unhandled rejection has occurred inside Forge:
Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
at getElectronPath (E:\CHATGPT-AI-Marketing-Tools-CMD\onepoint\node_modules\electron\index.js:17:11)
    at Object.<anonymous> (E:\CHATGPT-AI-Marketing-Tools-CMD\onepoint\node_modules\electron\index.js:21:18)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at locateElectronExecutable (E:\CHATGPT-AI-Marketing-Tools-CMD\onepoint\node_modules\@electron-forge\core\dist\util\electron-executable.js:34:28)
    at async forgeSpawn (E:\CHATGPT-AI-Marketing-Tools-CMD\onepoint\node_modules\@electron-forge\core\dist\api\start.js:104:32)
    at async forgeSpawnWrapper (E:\CHATGPT-AI-Marketing-Tools-CMD\onepoint\node_modules\@electron-forge\core\dist\api\start.js:138:25)
    at async exports.default (E:\CHATGPT-AI-Marketing-Tools-CMD\onepoint\node_modules\@electron-forge\core\dist\api\start.js:170:21)
    at async E:\CHATGPT-AI-Marketing-Tools-CMD\onepoint\node_modules\@electron-forge\cli\dist\electron-forge-start.js:57:21
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by boxizen** [comment]
Currently I don't have a plan on this, but I'm willing to accept pull requests if anyone implements it.
